##Start - Info App

##End - Info A
services:
  service-a:
    image: service-a:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db.service-a.svc.cluster.local:5432/service_a
      - LOG_LEVEL=debug
    dependencies:
      - service-b
      - service-c