##Start - Info App
info.app.name=Assi disbursement business
info.app.description=disbursements
info.app.version=@project.version@
info.app.artifact= "@project.artifactId@"
info.app.group= "@project.groupId@"
info.app.lastBuildDate= "@timestamp@"
info.app.ci-build= "@ci.build.number@"
info.app.git-sha-1= "@buildNumber@"
##End - Info App
