spring:
  application:
    name: bankwithdrawal-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/withdrawal?retryWrites=true&w=majority


microservices-urls:
 
  api-account: http://localhost:8095/api/account
  api-transaction: http://localhost:8095/api/transaction


