spring:
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/credit?retryWrites=true&w=majority
      
microservices-urls:
  api-client: ${API_CLIENT_CONFIG}
