spring:

  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/creditcard?ssl=true&retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
	
microservices-urls:
  api-client: ${API_CLIENT_CONFIG}
