
spring:

  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/currentAccount?retryWrites=true&w=majority
      
microservices-urls:
  api-client: ${API_CLIENT_CONFIG}
  api-credit: ${API_CREDIT_CONFIG}
  api-creditcard: ${API_CREDITCARD_CONFIG}
  

