spring:
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE


