spring:

  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/reports?retryWrites=true&w=majority

microservices-urls:
  api-client: ${API_CLIENT_CONFIG}
  api-credit: ${API_CREDIT_CONFIG}
  api-account: ${API_ACCOUNT_CONFIG}
  api-creditcard: ${API_CREDITCARD_CONFIG}
  api-currentAcc: ${API_CURRENTACCOUNT_CONFIG}
  api-fixedtermsAcc: ${API_FIXEDTERMSACCOUNT_CONFIG}