spring:

  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/yanki?retryWrites=true&w=majority


microservices-urls:
  api-client: ${API_DEBITCARD_CONFIG}
