server:
  port: 8082
spring:
  application:
    name: account-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/accounts?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

health:
  config:
    enabled=false:

logging:
  config:
  file: logback-spring.xml


microservices-urls:
  api-client: http://localhost:8095/api/client
  api-credit: http://localhost:8095/api/credit
  api-creditcard: http://localhost:8095/api/creditcard



