spring:
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/accounts?retryWrites=true&w=majority
health:
  config:
    enabled=false:

logging:
  config:
  file: logback-spring.xml

microservices-urls:
  api-client: ${api_client_config}
  api-credit: ${api-credit_config}
  api-creditcard: ${api_creditcard_config}



