server:
  port: 8085
spring:
  application:
    name: bankcredit-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/credit?retryWrites=true&w=majority
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
