server:
  port: 8082
spring:
  application:
    name: bankaccounts-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/accounts?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

health:
  config:
    enabled=false:

logging:
  config:
  file: logback-spring.xml






