spring:
  application:
    name: clients-microservice

  datasource:
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
    name: db_test_j1m3
    driver-class-name: org.h2.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"

client:
  api:
    token: apis-token-3973.dIIOAW5T1eWg4GhSVlloXLQkqh8axRec
    url: https://api.apis.net.pe/v1
