#server:
#  port: 8088

spring:
#  application:
#    name: creditcard-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/creditcard?retryWrites=true&w=majority

microservices-urls:
  api-client: http://localhost:8095/api/client
