server:
  port: 8088

spring:
  application:
    name: creditcard-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/creditcard?retryWrites=true&w=majority


