server:
  port: 8088

spring:
  application:
    name: creditcard-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/creditcard?ssl=true&retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
      
microservices-urls:
  api-client: http://localhost:8095/api/client
