server:
  port: 8086

spring:
  application:
    name: transfer-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/transfer?retryWrites=true&w=majority


