server:
  port: 8087

spring:
  application:
    name: transaction-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/transactions?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://192.168.101.7:8761/eureka
