server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/accounts?ssl=true&retryWrites=true&w=majority
health:
  config:
    enabled=false:

logging:
  config:
  file: logback-spring.xml
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

microservices-urls:
  api-client: http://localhost:8095/api/client
  api-credit: http://localhost:8095/api/credit
  api-creditcard: http://localhost:8095/api/creditcard