server:
  port: 8096

spring:
  application:
    name: bootcoin-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/bootcoin?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

microservices-urls:
  api-yanki: http://localhost:9095/api/yanki-account

  api-bootcoin-transac: http://localhost:9095/api/bootcoin-transaction
