spring:
 
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/fixedterms?retryWrites=true&w=majority
      
  
microservices-urls:
  api-client: http://localhost:8095/api/client
  api-credit: http://localhost:8095/api/credit
  api-creditcard: http://localhost:8095/api/creditcard
  
