server:
  port: 8090

spring:
  application:
    name: productreport-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/reports?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

microservices-urls:
  api-client: http://localhost:8095/api/client
  api-credit: http://localhost:8095/api/credit
  api-account: http://localhost:8095/api/account
  api-creditcard: http://localhost:8095/api/creditcard
  api-currentAcc: http://localhost:8095/api/currentAccount
  api-fixedtermsAcc: http://localhost:8095/api/fixedTermAccount
