server:
  port: 8093

spring:
  application:
    name: yanki-microservice
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/yanki?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

microservices-urls:
  api-debitcard: http://localhost:8095/api/debitcard
 