azure:
  tenant:
    id : 360bc517-7aac-4c17-9907-4c5f13a12289
    name: nubefalsa

pacifico:
  region: USA
  hora: true
  timezone: 'America/Los_Angeles'
  latitude: 'America/Limon'
  ga: 'gaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeee'
