# application.yml
environment:
  dev:
    database:
      host: localhost
      port: 5432
      username: dev_user
      password: dev_password
      name: dev_db
    features:
      logging: true
      caching: false
      betaFeature: true
  staging:
    database:
      host: staging-db.example.com
      port: 5432
      username: staging_user
      password: staging_password
      name: staging_db
    features:
      logging: true
      caching: true
      betaFeature: false
  prod:
    database:
      host: prod-db.example.com
      port: 5432
      username: prod_user
      password: prod_password
      name: prod_db
    features:
      logging: true
      caching: true
      betaFeature: false
